# -*- coding: utf-8 -*-
"""Ejercicio-2-prueba

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQG7DsQTi7Hh5tCH400G0zOfelUdIO6P
"""





libros = 150
prestamos = 0

print("Bienvenido al sistema akashico de la Biblioteca de alengandria")

while True:

    print("\n=== MENÚ PRINCIPAL ===")
    print("1. Libros disponibles")
    print("2. Realizar préstamo")
    print("3. Devolver préstamo")
    print("4. Historial de préstamos")
    print("5. Salir")

    opcion = input("Ingrese una opción: ")

    if opcion == "1":
        print("Libros disponibles:", libros)

    elif opcion == "2":
        cantidad = int(input("Cantidad de libros a prestar: "))

        if cantidad > 0 and cantidad <= libros:
            libros = libros - cantidad
            prestamos = prestamos + cantidad
            print("Préstamo realizado")
        else:
            print("no hay sufiente stock")

    elif opcion == "3":
        cantidad = int(input("Cantidad de libros a devolver: "))

        if cantidad > 0 and libros + cantidad <= 150:
            libros = libros + cantidad
            prestamos = prestamos - cantidad
            print("Devolución realizada")
        else:
            print("no hay sufiente stock")

    elif opcion == "4":
        print("Préstamos activos:", prestamos)

    elif opcion == "5":
        print("Gracias por utilizar  nuestro programa de gestion de libros ")
        break

    else:
        print("Opción incorrecta")